<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <div class="control-qty-wrapper">
                            <span class="minus"><span class="material-symbols-outlined">remove</span></span>
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   min="0"
                                   value="<?= $block->getProductDefaultQty() * 1 ?>"
                                   title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                   class="input-text qty"
                                   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                            />
                            <span class="plus"><span class="material-symbols-outlined">add</span></span>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <div class="actions-addtocart">
        <button type="submit"
                title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                class="action primary tocart"
                id="product-addtocart-button" disabled>
            <span><?= $block->escapeHtml($buttonTitle) ?></span>
        </button>
        <?php echo $block->getLayout()->createBlock('Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist')->setProduct($_product)->setTemplate("Magento_Wishlist::catalog/product/list/addto/wishlist.phtml")->toHtml(); ?>
        <?= $block->getChildHtml('', true) ?>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script type="text/javascript">
    require(['jquery'],function($) {
        $(document).ready(function(){
            $(".minus").click(function (e){
                let currentVal = parseInt($("#qty").val());
                if (currentVal > 1) {
                    $("#qty").val(currentVal-1);
                }
            });
            $(".plus").click(function (e){
                let currentVal = parseInt($("#qty").val());
                $("#qty").val(currentVal+1);
            });
        });
    });
</script>
