<div class="home-cate-wrapper">
    <div class="home-cate left">
        <div class="cate-inner">
            <h3 style="height: 45px;">Oral Supplements</h3>
            <p style="height: 112px;">Skin health starts from within<br>Strengthen your skin elasticity and radiance with oral supplements specially formulated to boost the quality of your skin</p>
            <p>
                <a title="LEARN MORE" href="http://muffin.magento.mg/professional-products/uv-porcelain.html/" style="height: 22px;">LEARN MORE</a>
            </p>
        </div>
    </div>
    <div class="home-cate mid">
        <div class="cate-inner">
            <h3 style="height: 45px;">Skin Care</h3>
            <p style="height: 112px;">Your skin deserves the best care<br>Develop a skincare routine that works for your specific skin type and addresses your personal skin concerns.</p>
            <p>
                <a title="SHOP NOW" href="http://muffin.magento.mg/e-shop.html/" style="height: 22px;">SHOP NOW</a>
            </p>
        </div>
    </div>
    <div class="home-cate right">
        <div class="cate-inner">
            <h3 style="height: 45px;">Makeup</h3>
            <p style="height: 112px;">Makeup that helps your skin shine<br>Enhance your look with makeup that cares for your skin. Consciously crafted with no nasty ingredients, find the right makeup products that leave your skin looking and feeling good.</p>
            <p>
                <a title="SHOP NOW" href="http://muffin.magento.mg/e-shop/makeup.html/" style="height: 22px;">SHOP NOW</a>
            </p>
        </div>
    </div>
</div>
