<div class="block-left-contact">
    <div class="block-content-contact">
        <div class="block-top-contact">
            <div class="info-title-contact">Send us an email</div>
            <div class="info-contact">If you have any enquiry, please do not hesitate to contact us. Leave us a message and we will get back to you shortly.<br><br>Operating Hours: 10am–6pm<br>Monday–Friday (except public holidays)</div>
        </div>
        <div class="block-bottom-contact">
            <div class="info-title-contact">Get in touch with us</div>
            <div class="info-contact-bottom">
                <div class="contact-line">
                    <i class="fas fa-map-marker-alt"></i>
                    <div id="contact-address"> 8 Ang Mo Kio Industrial Park 2 Singapore 569500</div>
                </div>
                <div class="contact-line">
                    <div><i class="fas fa-phone"></i><span> +65 1234 5678</span></div>
                </div>
                <div class="contact-line">
                    <div><i class="fas fa-envelope"></i><span> muffin@example.com</span></div>
                </div>
            </div>
        </div>
    </div>
</div>
