<div class="bottom_footer">
    <div class="container">
        <div class="copyrights">
            <p>Copyright © <span id="copy-year">2022</span> Curatiq Pte Ltd. All rights reserved.<span class="vez-title">Web Excellence by <a class="icon-vez" href="https://www.curatiq.com/webagency/" target="_blank" rel="noopener">Muffin(ノ^∇^)</a></span></p>
        </div>
        <div class="payment_method"><ul>
                <li><img src="https://www.curatiq.com/pub/media/paypal.png" alt=""></li>
                <li><img src="https://www.curatiq.com/pub/media/visa.png" alt=""></li>
                <li><img src="https://www.curatiq.com/pub/media/mastercard.png" alt=""></li>
                <li><img src="https://www.curatiq.com/pub/media/american-express.png" alt=""></li>
            </ul>
        </div>
    </div>
</div>
