<div class="col-footer footer_stay_connected"><h3>Stay Connected</h3>
    <ul>
        <li class="facebook"><a title="Facebook" href="https://www.facebook.com/curatiq" target="_blank" rel="noopener">Facebook</a></li>
        <li class="instagram"><a title="Instagram" href="https://www.instagram.com/curatiq" target="_blank" rel="noopener">Instagram</a></li>
    </ul>
</div>
<div class="col-footer footer_shop"><h3>Shop</h3>
    <ul>
        <li><a href="http://muffin.magento.mg/e-shop.html/">All Products</a></li>
        <li><a href="http://muffin.magento.mg/gift-card.html/">Gift Card</a></li>
    </ul>
</div>
<div class="col-footer footer_company"><h3>Company</h3>
    <ul>
        <li><a title="About Us" href="http://muffin.magento.mg/about-us.html/">About Us</a></li>
        <li><a title="Press" href="http://muffin.magento.mg/press.html/">Press</a></li>
        <li><a title="Journal" href="http://muffin.magento.mg/blog.html/">Journal</a></li>
        <li><a title="Sitemap" href="http://muffin.magento.mg/blog/sitemap.html/">Sitemap</a></li>
        <li><a title="Terms &amp; Conditions" href="http://muffin.magento.mg/terms-conditions/">Terms &amp; Conditions</a></li>
        <li><a title="Privacy Policy" href="http://muffin.magento.mg/privacy-policy-cookie-restriction-mode/">Privacy Policy</a></li>
    </ul>
</div>
<div class="col-footer footer_customer_service"><h3>Customer Service</h3>
    <ul>
        <li><a title="FAQs" href="http://muffin.magento.mg/<?php echo $this->helper('Muffin\FAQ\Helper\Data')->getConfig()['routerName'];?>/">FAQs</a></li>
        <li><a title="Shipping &amp; Delivery" href="http://muffin.magento.mg/shipping-delivery.html/">Shipping &amp; Delivery</a></li>
        <li><a title="Returns &amp; Exchanges" href="http://muffin.magento.mg/returns-exchanges.html/">Returns &amp; Exchanges</a></li>
        <li><a title="Contact Us" href="http://muffin.magento.mg/contact-us.html/">Contact Us</a></li>
    </ul>
</div>
