<div class="footer_guaranteed">
    <div class="container"><div class="main_guaranteed">
            <ul>
                <li>
                    <div class="guaranteed_item"><img src="https://www.curatiq.com/pub/media/guaranteed.svg" alt=""><div class="guaranteed_title">Authenticity Guarantee</div></div>
                </li>
                <li>
                    <div class="guaranteed_item"><img src="https://www.curatiq.com/pub/media/secure-shopping.svg" alt=""><div class="guaranteed_title">Secure Shopping Guarantee</div></div>
                </li>
                <li>
                    <div class="guaranteed_item"><img src="https://www.curatiq.com/pub/media/fast.svg" alt=""><div class="guaranteed_title">Fast Delivery</div></div>
                </li>
            </ul>
        </div>
    </div>
</div>
