<div class="item">
    <div class="container" style="position:relative">
        <img src="<?php echo $this->getViewFileUrl('images/Thank_you_Banner.png'); ?>" alt="" />
    </div>
    <div class="text-thank">
        <div class="general-thanks">
            <div class="title-thank">
                <h1>Thank You <span class="down-text"> for Your Enquiry</span></h1>
            </div>
            <div class="thank-info">
                <div class="content-thank">
                    <p>We have received your comments and have sent a confirmation email to your inbox. We thank you for your enquiry and will respond to you shortly.</p>
                </div>
                <div class="btn-general">
                    <div class="btn-ourservices"><a class="action submit primary" href="http://muffin.magento.mg/">Back to Home</a></div>
                    <div class="btn-ourservices"><a class="button" href="http://muffin.magento.mg/e-shop.html/">E-SHOP</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
